-- Contact form submissions.
-- Generated by letting Payload's dev push create the table, then copying
-- its DDL verbatim, so the schema matches what Payload expects at runtime.

CREATE TABLE IF NOT EXISTS `contact_requests` (
	`id` integer PRIMARY KEY NOT NULL,
	`status` text DEFAULT 'new' NOT NULL,
	`notes` text,
	`name` text NOT NULL,
	`email` text,
	`phone` text,
	`message` text,
	`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL
);
CREATE INDEX IF NOT EXISTS `contact_requests_status_idx` ON `contact_requests` (`status`);
CREATE INDEX IF NOT EXISTS `contact_requests_name_idx` ON `contact_requests` (`name`);
CREATE INDEX IF NOT EXISTS `contact_requests_email_idx` ON `contact_requests` (`email`);
CREATE INDEX IF NOT EXISTS `contact_requests_updated_at_idx` ON `contact_requests` (`updated_at`);
CREATE INDEX IF NOT EXISTS `contact_requests_created_at_idx` ON `contact_requests` (`created_at`);
